uc_bridge:
  ros__parameters:
    water_tank_frame: water_tank
    nutri_tank_frame: nutri_tank
    port: /dev/ttyAMA0
    max_recv_errors: 10

temperature_observer:
  ros__parameters:
    
    water_tank_frame: water_tank
    water_tank_sensor_addr: ""
    min_water_temp: 0.0
    max_water_temp: 0.0

    nutri_tank_frame: nutri_tank
    nutri_tank_sensor_addr: "28-0416b07a36ff"
    min_nutri_temp: 0.0
    max_nutri_temp: 0.0

    max_recv_errors: 10

/water_tank:
  level_observer:
    ros__parameters:
      frame_id: water_tank
      min_level: 0.05
      max_level: 0.2
      check_period: 1.0
      value_invalidate_time: 5.0

      closure_sensor_pin: 27
      led_pin: 2
      button_pin: 17
      
  pump_driver:
    ros__parameters:
      pump_pin: 3

/nutri_tank:
  level_observer:
    ros__parameters:
      frame_id: nutri_tank
      min_level: 0.05
      max_level: 0.2
      check_period: 1.0
      value_invalidate_time: 5.0

      closure_sensor_pin: 9
      led_pin: 10
      button_pin: 11

  pump_driver:
    ros__parameters:
      pump_pin: 25

  quality_observer:
    ros__parameters:
      frame_id: nutri_tank

      check_period: 1.0

      min_ppm: 0.0
      max_ppm: 0.0
      ppm_value_invalidate_time: 5.0

      min_ph: 0.0
      max_ph: 0.0
      ph_value_invalidate_time: 5.0
      
      led_pin: 22