#pragma once

#define ERROR_PIN DT_ALIAS(led0) // Red LED
#define BLINK_PIN DT_ALIAS(led1) // Green LED

#define WATER_PIN DT_ALIAS(driver_water)
#define NUTRI_PIN DT_ALIAS(driver_nutri)
#define FAN_PIN DT_ALIAS(driver_fan)

#define ZIGBEE_IDENTIFY_MODE_BUTTON DK_BTN1_MSK
#define ZIGBEE_FACTORY_RESET_BUTTON ZIGBEE_IDENTIFY_MODE_BUTTON
#define ZIGBEE_IDENTIFY_LED_PIN DT_ALIAS(led2) // Blue LED

#define SENSOR_TEMP_CELSIUS_MIN -40
#define SENSOR_TEMP_CELSIUS_MAX 85
#define SENSOR_TEMP_CELSIUS_TOLERANCE 1

#define SENSOR_PRESSURE_KPA_MIN 30
#define SENSOR_PRESSURE_KPA_MAX 110
#define SENSOR_PRESSURE_KPA_TOLERANCE 0

#define SENSOR_HUMIDITY_PERCENT_MIN 10
#define SENSOR_HUMIDITY_PERCENT_MAX 90