#pragma once

//#define DATASET_COLLECTOR

#ifdef DATASET_COLLECTOR
#define MAIN_LOG_LEVEL LOG_LEVEL_ERR
#define GPIO_LOG_LEVEL LOG_LEVEL_ERR
#define SENSORS_LOG_LEVEL LOG_LEVEL_ERR
#define CONTROLLERS_LOG_LEVEL LOG_LEVEL_ERR
#define ZIGBEE_LOG_LEVEL LOG_LEVEL_ERR
#define CLASSIFIER_LOG_LVL LOG_LEVEL_ERR
#else
#define MAIN_LOG_LEVEL LOG_LEVEL_INF
#define GPIO_LOG_LEVEL LOG_LEVEL_INF
#define SENSORS_LOG_LEVEL LOG_LEVEL_DBG
#define CONTROLLERS_LOG_LEVEL LOG_LEVEL_DBG
#define ZIGBEE_LOG_LEVEL LOG_LEVEL_DBG
#define CLASSIFIER_LOG_LVL LOG_LEVEL_DBG
#endif

#define LIGHT_CTRL_THREAD_STACK_SIZE 512