#pragma once

#define BASIC_APP_VER 1
#define BASIC_ZB_STACK_VER 10
#define BASIC_HW_VER 1
#define BASIC_MANUF_NAME "Nordic"
#define BASIC_MODEL_ID "FC_v0.1"
#define BASIC_DATE_CODE "20220914"
#define BASIC_POWER_SOURCE ZB_ZCL_BASIC_POWER_SOURCE_DC_SOURCE
#define BASIC_LOCATION "Field"
#define BASIC_ENV ZB_ZCL_BASIC_ENV_UNSPECIFIED

#define ZIGBEE_NETWORK_STATE_LED DK_LED2
//#define IDENTIFY_LED DK_LED3
#define IDENTIFY_MODE_BUTTON DK_BTN1_MSK
#define FACTORY_RESET_BUTTON IDENTIFY_MODE_BUTTON

#define ZB_FAN_ENDPOINT 10
#define ZB_LED1_ENDPOINT 11
#define ZB_LED2_ENDPOINT 12
#define ZB_STRATEGY_ENDPOINT 13
#define ZB_WATER_ENDPOINT 14
#define ZB_NUTRI_ENDPOINT 15

#define ZB_DEV_ID 0x2137
#define ZB_DEV_VER 1

#define ZB_IN_CLUSTER_NUM 10
#define ZB_OUT_CLUSTER_NUM 0 // TODO: Change